apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluenginx
  labels:
    app: nginx
spec:
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 10
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: bluenginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: bluenginx
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 20
