apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxhello
  labels:
    app: nginxhello
spec:
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 10
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: nginxhello
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nginxhello
    spec:
      containers:
        - name: nginxhello
          image: nginxdemos/nginx-hello
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: nginxhello-svc
spec:
  selector:
    app: nginxhello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: nginxhello
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: nginxhello
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 20
