kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: bluenginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: bluenginx
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 20
