apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Chart.Name }}-pv"
spec:
  capacity:
    storage: {{ .Values.database.persistentVolume.capacity }}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: {{ .Values.database.persistentVolume.hostPath }}
    type: Directory