apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssqlsvr.fullname" . }}
  labels:
    {{- include "mssqlsvr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mssql
      protocol: TCP
      name: mssql
  selector:
    {{- include "mssqlsvr.selectorLabels" . | nindent 4 }}
