apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: neb-new-job
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        id: awesome-job
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - sleep 2 && echo done
        image: busybox
        name: neb-new-job-container
        resources: {}
      restartPolicy: Never
status: {}
