apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: position-groups
  labels:
    app: my-nginx
spec:
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 10
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
        - name: my-nginx
          image: nginx:stable
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
spec:
  selector:
    app: my-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer