apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: swagger-ui-nitro
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: swagger-ui-nitro
              servicePort: 80
