apiVersion: v1
kind: Pod
metadata:
  name: swagger-test-pod
spec:
  containers:
    - name: test-container
      image: swaggerapi/swagger-ui
      command: ["/bin/sh", "-c", "cat /etc/config/keys"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: swagger-configmap
        items:
          - key: swagger.yaml
            path: keys
  restartPolicy: Never
