apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fruit
  name: fruit
spec:
  volumes:
    - name: config-haproxy
      configMap:
        name: fruit-service-ambassador-config
  containers:
  - image: linuxacademycontent/legacy-fruit-service:1
    name: fruit
  - image: haproxy:1.7
    name: haproxy-ambassoder
    volumeMounts:
      - name: config-haproxy
        mountPath: /usr/local/etc/haproxy
