# ambassoderA
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ambass
  name: ambass
spec:
  volumes:
    - name: ha-config-vol
      configMap:
        name: haproxy-config
  containers:
  - image: mykplabs/kubernetes:nginx
    name: ambass
  - image: haproxy:1.7
    name: haproxy-container
    ports:
      - containerPort: 80
    volumeMounts:
      - name: ha-config-vol
        mountPath: /usr/local/etc/haproxy/haproxy.cfg

