apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  initContainers:
  - name: install
    image: busybox
    args:
    - /bim/sh
    - -c
    - wget -O /work-dir/index.html http://neverssl.com/online
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - name: workdir
      mountPath: "/usr/share/nginx/html"
  dnsPolicy: ClusterFirst
  volumes:
  - name: workdir
    emptyDir: {}
  restartPolicy: Always
status: {}