{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nitro-swagger.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "nitro-swagger.labels" . | indent 4 }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/success-codes: 200-499
  {{- if .Values.clusterData.niteALBSecurityGroup  }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.clusterData.niteALBSecurityGroup }}
  {{- end }}
  {{- if .Values.clusterData.niteWebAclId  }}
    alb.ingress.kubernetes.io/waf-acl-id: {{ .Values.clusterData.niteWebAclId }}
  {{- end }}

spec:
  rules:
    - host: {{ include "nitro-swagger.fullname" . }}.{{ .Values.clusterData.clusterInfo }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: {{ include "nitro-swagger.fullname" . }}
              servicePort: 80
{{- end }}