apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secrets-pod-volume
  name: secrets-pod-volume
spec:
  containers:
  - image: nginx
    resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
    name: secrets-pod-volume
    volumeMounts:
      - mountPath: "/etc/foo"
        name: foo
  volumes:
    - name: foo
      secret: 
        secretName: firstsecret
   