# kubectl create secret generic kplabs-secret --from-literal=user=admin --from-literal=pass=12345
apiVersion: v1
kind: Pod
metadata:
  name: kplabs-secret-from-env-test
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kplabs-secret
              key: pass
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: kplabs-secret
              key: user
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
